# Generated by Django 3.2.18 on 2023-03-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='categories')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FF0000', 'Red'), ('00FFFF', 'Cyan'), ('0000FF', 'Blue'), ('800080', 'Purple'), ('FFFF00', 'Yellow'), ('FFFFFF', 'White'), ('000000', 'Black'), ('008000', 'Green'), ('C0C0C0', 'Silver'), ('FF00FF', 'Magenta'), ('FFA500', 'Orange'), ('800000', 'Maroon'), ('808000', 'Olive')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('price', models.PositiveIntegerField()),
                ('new_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('price_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.BooleanField(default=False)),
                ('type_cash', models.CharField(max_length=255)),
                ('return_day', models.PositiveIntegerField()),
                ('made_in', models.CharField(max_length=255)),
                ('made_in_ru', models.CharField(max_length=255, null=True)),
                ('made_in_uz', models.CharField(max_length=255, null=True)),
                ('made_in_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('characteristic', models.CharField(max_length=255)),
                ('characteristic_ru', models.CharField(max_length=255, null=True)),
                ('characteristic_uz', models.CharField(max_length=255, null=True)),
                ('characteristic_en', models.CharField(max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=models.SET('No brand'), related_name='product', to='product.brand')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product.Color'),
        ),
    ]
